import { Job, Application, ScreeningResult, AnalyticsSummary } from '@/types'

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-1',
    title: 'Senior Software Engineer',
    company: 'TechFlow Ltd',
    location: 'London, UK',
    type: 'full-time',
    description: 'We are looking for a Senior Software Engineer to join our growing team. You will work on challenging distributed systems problems and help shape our engineering culture.',
    requirements: ['5+ years React/Node.js', 'System design experience', 'TypeScript proficiency', 'Team leadership'],
    salary: '£80,000–£100,000',
    postedAt: '2026-02-20',
    status: 'open',
    applicants: 47,
    recruiterName: 'Sarah Collins',
  },
  {
    id: 'job-2',
    title: 'Product Manager',
    company: 'TechFlow Ltd',
    location: 'Remote',
    type: 'remote',
    description: 'Drive product strategy for our core platform. Work closely with engineering, design, and customers to build products people love.',
    requirements: ['3+ years PM experience', 'Technical background', 'Data-driven mindset', 'Excellent communication'],
    salary: '£70,000–£90,000',
    postedAt: '2026-02-22',
    status: 'open',
    applicants: 31,
    recruiterName: 'Sarah Collins',
  },
  {
    id: 'job-3',
    title: 'UX Designer',
    company: 'TechFlow Ltd',
    location: 'Manchester, UK',
    type: 'full-time',
    description: 'Design delightful experiences across our product suite. You will own end-to-end design from research to high-fidelity prototypes.',
    requirements: ['Portfolio of shipped products', 'Figma mastery', 'User research skills', '2+ years experience'],
    salary: '£55,000–£70,000',
    postedAt: '2026-02-25',
    status: 'open',
    applicants: 18,
    recruiterName: 'James Park',
  },
]

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'app-1',
    jobId: 'job-1',
    jobTitle: 'Senior Software Engineer',
    company: 'TechFlow Ltd',
    candidateName: 'Jordan Mitchell',
    candidateEmail: 'jordan.m@email.com',
    status: 'screened',
    appliedAt: '2026-02-21',
    result: {
      id: 'res-1',
      applicationId: 'app-1',
      score: 72,
      skillsMatch: 78,
      experienceMatch: 66,
      decision: 'rejected',
      feedback: 'Your technical skills in React and Node.js are a strong match for this role. The primary gap identified was in team leadership — the role requires demonstrable experience managing cross-functional teams of 5+ people, which was not evident from your CV. We also noticed your experience with distributed systems is mostly theoretical. We would encourage you to apply again once you have acquired more leadership experience.',
      biasFlags: [
        { type: 'Age Proxy', description: 'Graduation year used as indirect age indicator in scoring', severity: 'medium' },
      ],
      skillGaps: ['Team leadership (2+ years)', 'Distributed systems (production)', 'System design interviews'],
      strengths: ['React & TypeScript expertise', 'Testing culture', 'Clear project impact metrics'],
      processedAt: '2026-02-21T14:30:00Z',
    },
  },
  {
    id: 'app-2',
    jobId: 'job-1',
    jobTitle: 'Senior Software Engineer',
    company: 'TechFlow Ltd',
    candidateName: 'Priya Sharma',
    candidateEmail: 'priya.s@email.com',
    status: 'shortlisted',
    appliedAt: '2026-02-21',
    result: {
      id: 'res-2',
      applicationId: 'app-2',
      score: 91,
      skillsMatch: 94,
      experienceMatch: 88,
      decision: 'shortlisted',
      feedback: 'Excellent match. Strong leadership track record and deep technical expertise align closely with our requirements.',
      biasFlags: [],
      skillGaps: [],
      strengths: ['8 years engineering', 'Led team of 12', 'Open source contributions', 'System design expertise'],
      processedAt: '2026-02-21T14:32:00Z',
    },
  },
  {
    id: 'app-3',
    jobId: 'job-1',
    jobTitle: 'Senior Software Engineer',
    company: 'TechFlow Ltd',
    candidateName: 'Marcus Webb',
    candidateEmail: 'marcus.w@email.com',
    status: 'screened',
    appliedAt: '2026-02-22',
    result: {
      id: 'res-3',
      applicationId: 'app-3',
      score: 58,
      skillsMatch: 61,
      experienceMatch: 55,
      decision: 'rejected',
      feedback: 'While your enthusiasm is clear, the role requires deeper experience with TypeScript and production Node.js systems. Your 2 years of experience falls short of the 5+ years required. We recommend building more production-scale experience before reapplying.',
      biasFlags: [
        { type: 'Name Bias Risk', description: 'Name-based demographic inference detected in initial scoring pass', severity: 'low' },
      ],
      skillGaps: ['TypeScript (advanced)', 'Production Node.js', 'Team leadership', '3+ more years experience'],
      strengths: ['Strong problem-solving', 'Good communication skills', 'Eagerness to learn'],
      processedAt: '2026-02-22T09:15:00Z',
    },
  },
  {
    id: 'app-4',
    jobId: 'job-2',
    jobTitle: 'Product Manager',
    company: 'TechFlow Ltd',
    candidateName: 'Aisha Okafor',
    candidateEmail: 'aisha.o@email.com',
    status: 'shortlisted',
    appliedAt: '2026-02-23',
    result: {
      id: 'res-4',
      applicationId: 'app-4',
      score: 87,
      skillsMatch: 89,
      experienceMatch: 85,
      decision: 'shortlisted',
      feedback: 'Strong product sense and solid track record of shipping. Moving forward to interview stage.',
      biasFlags: [],
      skillGaps: ['SQL (advanced analytics)'],
      strengths: ['4 years PM at scale', 'Data-driven decisions', 'Cross-functional leadership'],
      processedAt: '2026-02-23T11:00:00Z',
    },
  },
]

export const MOCK_ANALYTICS: AnalyticsSummary = {
  totalApplications: 247,
  screened: 231,
  shortlisted: 43,
  rejected: 188,
  biasDetected: 17,
  avgScore: 61,
}

export const BIAS_TREND_DATA = [
  { month: 'Sep', flagged: 8, total: 34 },
  { month: 'Oct', flagged: 12, total: 41 },
  { month: 'Nov', flagged: 7, total: 38 },
  { month: 'Dec', flagged: 5, total: 29 },
  { month: 'Jan', flagged: 9, total: 52 },
  { month: 'Feb', flagged: 17, total: 53 },
]

export const BIAS_TYPES_DATA = [
  { type: 'Age Proxy', count: 7, color: '#f0c040' },
  { type: 'Name Bias', count: 5, color: '#e8851a' },
  { type: 'Gender Proxy', count: 3, color: '#c84b31' },
  { type: 'University Bias', count: 2, color: '#5a3ea1' },
]
